name: Deploy CMS to Vercel

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      DOTENV:       ${{ secrets.DOTENV }}
      GITEA_TOKEN:  ${{ secrets.GITEA_TOKEN }}

    steps:
      - name: Checkout source
        uses: https://github.com/actions/checkout@v4

      - name: Setup Node.js 20 + Yarn cache
        uses: https://github.com/actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Show where we are building
        run: |
          echo "CI on: ${GITHUB_SERVER_URL:-gitea.local?} (runner side)"
          node -v && yarn -v

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel env (production)
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

      - name: Config Gitea Token for HTTPS installs (runner side)
        if: ${{ env.GITEA_TOKEN != '' }}
        run: |
          git config --global url."https://oauth2:${GITEA_TOKEN}@gitea.sev-2.com/".insteadOf "https://gitea.sev-2.com/"
          git config --global url."https://oauth2:${GITEA_TOKEN}@gitea.sev-2.com/".insteadOf "ssh://gitea.sev-2.com/"
          git config --global url."https://oauth2:${GITEA_TOKEN}@gitea.sev-2.com/".insteadOf "git@gitea.sev-2.com:"

      - name: Write .env from DOTENV secret
        run: printf '%s\n' "$DOTENV" > .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build (production)
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          CI: 'true'
        run: vercel build --prod --token="$VERCEL_TOKEN"

      - name: Deploy to Vercel (production)
        run: vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
