name: Deploy CMS to Vercel

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: vercel-prod-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      DOTENV:       ${{ secrets.DOTENV }}
      GITEA_TOKEN:  ${{ secrets.GITEA_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 20 + Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel env (production)
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

      - name: Config Gitea Token for install dependencies
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          for from in \
            "https://gitea.sev-2.com/" "https://gitea.sev-2.com" \
            "ssh://gitea.sev-2.com/"   "ssh://gitea.sev-2.com" \
            "ssh://git@gitea.sev-2.com/" "ssh://git@gitea.sev-2.com" \
            "git@gitea.sev-2.com:" "git+ssh://gitea.sev-2.com/" "git+ssh://gitea.sev-2.com"
          do
            git config --global url."https://${GITEA_TOKEN}@gitea.sev-2.com/".insteadOf "$from"
          done
          # Debug (boleh hapus nanti)
          git config --global -l | grep -E 'url\..*gitea' || true

      - name: Write .env from DOTENV secret
        run: |
          printf '%s\n' "$DOTENV" > .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build (production)
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          CI: 'true'
        run: vercel build --prod --token="$VERCEL_TOKEN"

      - name: Deploy to Vercel (production)
        run: vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
